# Generated by Django 4.0.4 on 2022-05-23 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customuser_pesel_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ManyToManyField(related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='comment',
            name='doctor',
            field=models.ManyToManyField(related_name='commented_doc', to=settings.AUTH_USER_MODEL),
        ),
    ]
