# Generated by Django 4.0.4 on 2022-05-23 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_comment_author_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='comment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='comment',
            name='doctor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='commented_doc', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
