# Generated by Django 4.0.4 on 2022-06-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_doctorprofile_spec2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='spec1',
            field=models.CharField(choices=[('kardiolog', 'Kardiolog'), ('kardiochirurg', 'Kardiochirurg')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='spec2',
            field=models.CharField(blank=True, choices=[('kardiolog', 'Kardiolog'), ('kardiochirurg', 'Kardiochirurg')], max_length=50, null=True),
        ),
    ]
