# Generated by Django 4.0.4 on 2022-06-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_doctorprofile_spec1_alter_doctorprofile_spec2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hour',
            field=models.TimeField(choices=[('8', '8:00'), ('8:30', '8:30'), ('9', '9:00'), ('9:30', '9:30'), ('10', '10:00'), ('10:30', '10:30'), ('11', '11:00'), ('11:30', '11:30'), ('12', '12:00'), ('12:30', '12:30'), ('13', '13:00'), ('13:30', '13:30'), ('14', '14:00'), ('14:30', '14:30'), ('15', '15:00'), ('15:30', '15:30'), ('16', '16:00'), ('16:30', '16:30'), ('17', '17:00'), ('17:30:00', '17:30:00'), ('18', '18:00'), ('18:30', '18:30'), ('19', '19:00'), ('19:30', '19:30'), ('20', '20:00'), ('20:30', '20:30')]),
        ),
    ]
