# Generated by Django 4.0.4 on 2022-06-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_appointment_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='PWZ_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
