# Generated by Django 4.0.4 on 2022-06-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_doctorprofile_pwz_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isDoctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='PWZ_number',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
    ]
