# Generated by Django 4.0.4 on 2022-06-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_customuser_isdoctor_alter_doctorprofile_pwz_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='PWZ_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
