# Generated by Django 4.0.4 on 2022-06-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_doctorprofile_pwz_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cause',
            field=models.TextField(default='Koncza mi sie leki', verbose_name='Powód wizyty'),
            preserve_default=False,
        ),
    ]
