# Generated by Django 4.0.4 on 2022-06-13 01:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_appointment_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Imię'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Dzień wizyty'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hour',
            field=models.TimeField(choices=[(datetime.time(8, 0), '8:00'), (datetime.time(8, 30), '8:30'), (datetime.time(9, 0), '9:00'), (datetime.time(9, 30), '9:30'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 30), '10:30'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00'), (datetime.time(20, 30), '20:30')], verbose_name='Godzina wizyty'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='Treść komentarza:'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adres zamieszkania'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Drugie imię'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='PWZ_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numer licencji lekarskiej'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='facility',
            field=models.CharField(max_length=255, verbose_name='Placówka'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='spec1',
            field=models.CharField(choices=[('kardiolog', 'Kardiolog'), ('kardiochirurg', 'Kardiochirurg'), ('ortopeda', 'Ortopeda'), ('fizjoterapeuta', 'Fizjoterapeuta'), ('psycholog', 'Psycholog'), ('psychoterapeuta', 'Psychoterapeuta'), ('psychiatra', 'Psychiatra'), ('psychiatra_dziecięcy', 'Psychiatra dziecięcy'), ('weterynarz', 'Weterynarz'), ('pediatra', 'Pediatra'), ('hepatolog', 'Hepatolog'), ('nefrolog', 'Nefrolog'), ('stomatolog', 'Stomatolog'), ('dermatolog', 'Dermatolog'), ('neurolog', 'Neurolog'), ('neurochirurg', 'Neurochirurg'), ('chirurg', 'Chirurg'), ('kardiochirurg', 'Kardiochirurg'), ('hematolog', 'Hematolog'), ('laryngolog', 'Laryngolog'), ('alergolog', 'Alergolog'), ('pulmunolog', 'Pulmunolog'), ('anestezjolog', 'Anestezjolog'), ('lekarz_rodzinny', 'Lekarz rodzinny'), ('lekarz_medycyny_pracy', 'Lekarz medycyny pracy'), ('gastrolog', 'Gastrolog'), ('ginekolog', 'Ginekolog'), ('endokrynolog', 'Endokrynolog')], max_length=50, verbose_name='Główna specjalizacja'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='spec2',
            field=models.CharField(blank=True, choices=[('kardiolog', 'Kardiolog'), ('kardiochirurg', 'Kardiochirurg'), ('ortopeda', 'Ortopeda'), ('fizjoterapeuta', 'Fizjoterapeuta'), ('psycholog', 'Psycholog'), ('psychoterapeuta', 'Psychoterapeuta'), ('psychiatra', 'Psychiatra'), ('psychiatra_dziecięcy', 'Psychiatra dziecięcy'), ('weterynarz', 'Weterynarz'), ('pediatra', 'Pediatra'), ('hepatolog', 'Hepatolog'), ('nefrolog', 'Nefrolog'), ('stomatolog', 'Stomatolog'), ('dermatolog', 'Dermatolog'), ('neurolog', 'Neurolog'), ('neurochirurg', 'Neurochirurg'), ('chirurg', 'Chirurg'), ('kardiochirurg', 'Kardiochirurg'), ('hematolog', 'Hematolog'), ('laryngolog', 'Laryngolog'), ('alergolog', 'Alergolog'), ('pulmunolog', 'Pulmunolog'), ('anestezjolog', 'Anestezjolog'), ('lekarz_rodzinny', 'Lekarz rodzinny'), ('lekarz_medycyny_pracy', 'Lekarz medycyny pracy'), ('gastrolog', 'Gastrolog'), ('ginekolog', 'Ginekolog'), ('endokrynolog', 'Endokrynolog')], max_length=50, null=True, verbose_name='Dodatkowa specjalizacja (opcjonalna)'),
        ),
    ]
