# Generated by Django 4.0.4 on 2022-07-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_appointment_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='PESEL',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(unique=True, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='PWZ_number',
            field=models.IntegerField(default=0, unique=True, verbose_name='Numer licencji lekarskiej'),
            preserve_default=False,
        ),
    ]
