# Generated by Django 4.0.4 on 2022-07-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_customuser_pesel_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='PWZ_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Numer licencji lekarskiej'),
        ),
    ]
