# Generated by Django 4.0.4 on 2022-07-09 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_doctorprofile_pwz_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='PESEL',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(90000000000), django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)], verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='PWZ_number',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Numer licencji lekarskiej'),
        ),
    ]
